[package]
name = "algo_testing"
version = "0.1.0"
authors = ["Paul Mana <paul@malikaz.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
debug = true

[dependencies]
